require('dotenv').config();
const express = require('express');
const cors = require('cors');
const axios = require('axios');

const app = express();

// Standard CORS options pointing specifically back to our frontend running locally.
app.use(cors());
app.use(express.json()); // Parses incoming JSON payloads 

app.post('/api/generate-headline', async (req, res) => {
  const { article, params = {} } = req.body;
  const token = process.env.HF_TOKEN;

  if (!token) {
    return res.status(500).json({ error: "Server missing Hugging Face Token" });
  }

  try {
    // The notebook shows the model expects "summarize: " prefixed to the input.
    const preprocessedArticle = `summarize: ${article}`;

    const response = await axios({
  method: "post",
  url: "https://api-inference.huggingface.co/models/himanshu0913/news-headline-generator",
  headers: {
    Authorization: `Bearer ${token}`,
    "Content-Type": "application/json",
  },
  data: {
    inputs: preprocessedArticle,
    parameters: {
      max_length: params.max_length || 20,
      min_length: params.min_length || 8,
      num_return_sequences: params.num_return_sequences || 1,
      num_beams: params.num_return_sequences > 1 ? 8 : 6,
      no_repeat_ngram_size: 2,
      length_penalty: 1.0
    }
  }
});
    // const response = await axios.post(
    //   'https://api-inference.huggingface.co/models/himanshu0913/news-headline-generator',
    //   {
    //     inputs: preprocessedArticle,
    //     parameters: {
    //       max_length: params.max_length || 20,          // Based on max_length=20 in notebook
    //       min_length: params.min_length || 8,           // Based on min_length=8 in notebook
    //       num_return_sequences: params.num_return_sequences || 1,
    //       num_beams: params.num_beams || (params.num_return_sequences > 1 ? 8 : 6), // 6 for single, 8 for multiple
    //       no_repeat_ngram_size: 2,
    //       early_stopping: false,
    //       length_penalty: 1.0,
    //       ...params
    //     },
    //     options: {
    //         wait_for_model: true
    //     }
    //   },
    //   {
    //     headers: {
    //       Authorization: `Bearer ${token}`,
    //       'Content-Type': 'application/json'
    //     },
    //     timeout: 120000
    //   }
    // );
    
    return res.json(response.data);
  } catch (error) {
    console.error("HF Error Details:", error.response?.data, error.message);
    // Properly proxy the exact error message we get from HF back to the client
    return res.status(500).json({ 
      error: error.response?.data?.error || error.message || "An error occurred with Hugging Face API",
      details: error.response?.data || {}
    });
  }
});

app.post('/api/improve-headline', async (req, res) => {
  const { article, currentHeadline } = req.body;
  const key = process.env.GEMINI_API_KEY;

  if (!key) {
    return res.status(500).json({ error: "Server missing Gemini API Key" });
  }

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${key}`;
  
  const prompt = `You are an expert news editor. The following headline was generated by an AI model but might be incomplete, cut-off, or lack context because it is trained on CNN/Dailymail datasets. 

Please fix, complete, and improve the headline to make it a concise, professional, and grammatically correct news headline based on the article provided. ONLY return the improved headline, nothing else.

Article summary/content:
${article}

Generated Headline to improve:
${currentHeadline}`;

  try {
    const response = await axios.post(
      url, 
      { contents: [{ parts: [{ text: prompt }] }] },
      { headers: { 'Content-Type': 'application/json' } }
    );

    if (response.data?.candidates?.[0]?.content?.parts?.[0]?.text) {
      return res.json({ 
        improvedText: response.data.candidates[0].content.parts[0].text.trim() 
      });
    }
    
    return res.json({ improvedText: currentHeadline }); // Fallback to original
    
  } catch (error) {
    console.error("Gemini Error:", error.response?.data || error.message);
    return res.status(500).json({ 
      error: error.response?.data?.error?.message || "Failed to contact Gemini API" 
    });
  }
});

const PORT = 5000;
app.listen(PORT, () => {
  console.log(`Backend server running on http://localhost:${PORT}`);
});
