# -*- coding: utf-8 -*-
"""NewsHeadlineGenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ONEgHeE_3T06bCdo75bKZAEkukZQXNW-
"""

# ls -lh /content/news_model.zip

# unzip -FF /content/news_model.zip -d /content/

import torch
torch.cuda.is_available()

# pip install transformers datasets evaluate rouge-score

# pip install -U transformers

import torch
from datasets import load_dataset
from transformers import T5Tokenizer, T5ForConditionalGeneration, Trainer, TrainingArguments

device = "cuda" if torch.cuda.is_available() else "cpu"

dataset = load_dataset("cnn_dailymail", "3.0.0")

print(dataset)

print(dataset["train"][0])

small_train = dataset["train"].shuffle(seed=42).select(range(50000))
small_val = dataset["validation"].shuffle(seed=42).select(range(2000))

tokenizer = T5Tokenizer.from_pretrained("t5-small")
model = T5ForConditionalGeneration.from_pretrained("t5-small").to(device)

def preprocess(example):
    inputs = ["summarize: " + article for article in example["article"]]
    targets = [h.split("\n")[0] for h in example["highlights"]]

    model_inputs = tokenizer(inputs, max_length=512, truncation=True, padding="max_length")
    labels = tokenizer(targets, max_length=64, truncation=True, padding="max_length")

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_train = small_train.map(preprocess, batched=True)
tokenized_val = small_val.map(preprocess, batched=True)

training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=100,
    fp16=True,
    load_best_model_at_end=True,
    save_total_limit=2
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
)

trainer.train()

def generate_headline(text):
    inputs = tokenizer("summarize: " + text, return_tensors="pt", truncation=True, max_length=512).to(device)

    with torch.no_grad():
        outputs = model.generate(
            inputs["input_ids"],
            max_length=12,
            num_beams=5,
            length_penalty=2.0,
            early_stopping=True
        )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# pip install evaluate

import evaluate
rouge = evaluate.load("rouge")

predictions = []
references = []

for i in range(100):  # you can increase later
    pred = generate_headline(dataset["test"][i]["article"])
    ref = dataset["test"][i]["highlights"].split("\n")[0]

    predictions.append(pred)
    references.append(ref)

results = rouge.compute(predictions=predictions, references=references)
print("ROUGE Scores:", results)

print("Generated:", generate_headline(dataset["test"][0]["article"]))
print("Actual:", dataset["test"][0]["highlights"])

model.save_pretrained("headline-model")
tokenizer.save_pretrained("headline-model")

import os
import shutil
from google.colab import files

# -----------------------------
# 1. Save model + tokenizer
# -----------------------------
save_directory = "news_model"

# Clean old directory if exists (avoids corrupted saves)
if os.path.exists(save_directory):
    shutil.rmtree(save_directory)

model.save_pretrained(save_directory)
tokenizer.save_pretrained(save_directory)

print(f"Model saved at: {save_directory}")

# -----------------------------
# 2. Create ZIP file
# -----------------------------
zip_path = shutil.make_archive(save_directory, 'zip', save_directory)

print(f"ZIP created at: {zip_path}")

# -----------------------------
# 3. Download ZIP
# -----------------------------
print("Downloading model...")
files.download(zip_path)

