# -*- coding: utf-8 -*-
"""NewsHeadlineGenerator (4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cth4VK763I81SWFdFtJAG4QWdS10xFIj
"""

import torch
torch.cuda.is_available()

!pip install transformers datasets evaluate rouge-score

!pip install -U transformers

import torch
from datasets import load_dataset
from transformers import T5Tokenizer, T5ForConditionalGeneration, Trainer, TrainingArguments

# drive.mount('/content/drive')

device = "cuda" if torch.cuda.is_available() else "cpu"

dataset = load_dataset("cnn_dailymail", "3.0.0")

print(dataset)

# model_path = "/content/drive/MyDrive/headline-model"

# tokenizer = T5Tokenizer.from_pretrained(model_path)
# model = T5ForConditionalGeneration.from_pretrained(model_path).to(device)

# print("Model loaded successfully")

print(dataset["train"][0])

small_train = dataset["train"].shuffle(seed=42).select(range(50000))
small_val = dataset["validation"].shuffle(seed=42).select(range(2000))

tokenizer = T5Tokenizer.from_pretrained("t5-small")
model = T5ForConditionalGeneration.from_pretrained("t5-small").to(device)

def preprocess(example):
    inputs = ["summarize: " + article for article in example["article"]]
    targets = [h.split("\n")[0] for h in example["highlights"]]

    model_inputs = tokenizer(inputs, max_length=512, truncation=True, padding="max_length")
    labels = tokenizer(targets, max_length=20, truncation=True, padding="max_length")

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_train = small_train.map(preprocess, batched=True)
tokenized_val = small_val.map(preprocess, batched=True)

training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=100,
    fp16=True,
    load_best_model_at_end=True,
    save_total_limit=2
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
)

trainer.train()

def generate_headline(text):
    inputs = tokenizer(
        "summarize: " + text,
        return_tensors="pt",
        truncation=True,
        max_length=512
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            inputs["input_ids"],
            num_beams=6,
            min_length=8,
            max_length=20,
            length_penalty=1.0,
            no_repeat_ngram_size=2,
            early_stopping=False
        )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

def generate_multiple_headlines(text, num_return_sequences=3):
    inputs = tokenizer(
        "summarize: " + text,
        return_tensors="pt",
        truncation=True,
        max_length=512
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            inputs["input_ids"],
            max_length=20,
            min_length=8,
            num_beams=8,
            num_return_sequences=num_return_sequences,
            no_repeat_ngram_size=2,
            early_stopping=False
        )

    headlines = [
        tokenizer.decode(output, skip_special_tokens=True)
        for output in outputs
    ]

    return headlines

def batch_generate_headlines(articles):
    results = []

    for article in articles:
        headline = generate_headline(article)
        results.append(headline)

    return results

import evaluate
rouge = evaluate.load("rouge")

predictions = []
references = []

for i in range(100):  # you can increase later
    pred = generate_headline(dataset["test"][i]["article"])
    ref = dataset["test"][i]["highlights"].split("\n")[0]

    predictions.append(pred)
    references.append(ref)

results = rouge.compute(predictions=predictions, references=references)
print("ROUGE Scores:", results)

print("Generated:", generate_headline(dataset["test"][10]["article"]))
print("Actual:", dataset["test"][10]["highlights"])

article = dataset["test"][0]["article"]

headlines = generate_multiple_headlines(article, 3)

for i, headline in enumerate(headlines, 1):
    print(f"{i}. {headline}")

articles = [
    dataset["test"][0]["article"],
    dataset["test"][1]["article"],
    dataset["test"][2]["article"]
]

headlines = batch_generate_headlines(articles)

for i, headline in enumerate(headlines, 1):
    print(f"Article {i}: {headline}")

!ls /content/drive/MyDrive

output_dir = "/content/drive/MyDrive/headline-model"
trainer.save_model(output_dir)
tokenizer.save_pretrained(output_dir)
print(f"Model and tokenizer saved to {output_dir}")

import os
import shutil
from google.colab import files

# -----------------------------
# 1. Save model + tokenizer
# -----------------------------
save_directory = "news_model"

# Clean old directory if exists (avoids corrupted saves)
if os.path.exists(save_directory):
    shutil.rmtree(save_directory)

model.save_pretrained(save_directory)
tokenizer.save_pretrained(save_directory)

print(f"Model saved at: {save_directory}")

# -----------------------------
# 2. Create ZIP file
# -----------------------------
zip_path = shutil.make_archive(save_directory, 'zip', save_directory)

print(f"ZIP created at: {zip_path}")

# -----------------------------
# 3. Download ZIP
# -----------------------------
print("Downloading model...")
files.download(zip_path)

!pip install huggingface_hub

from huggingface_hub import login
login()

from huggingface_hub import HfApi, upload_folder

repo_name = "news-headline-generator"

api = HfApi()

api.create_repo(
    repo_id=f"himanshu0913/{repo_name}",
    repo_type="model",
    exist_ok=True
)

upload_folder(
    folder_path="news_model",
    repo_id=f"himanshu0913/{repo_name}",
    repo_type="model"
)

print("Model uploaded successfully!")

from transformers import T5Tokenizer, T5ForConditionalGeneration

repo_id = "himanshu0913/news-headline-generator"

tokenizer = T5Tokenizer.from_pretrained(repo_id)
model = T5ForConditionalGeneration.from_pretrained(repo_id).to(device)

print("Loaded successfully from Hugging Face")

article = """
Global technology companies are increasing investments in artificial intelligence as competition in the sector continues to intensify. On Tuesday, a leading multinational software company announced a new suite of AI-powered productivity tools designed to automate repetitive office tasks, generate reports, and assist developers with code generation.

The company stated that the new tools will be integrated directly into its existing cloud ecosystem, allowing businesses to deploy AI assistants across email, documentation platforms, customer service workflows, and internal analytics dashboards.

Industry analysts believe this move is part of a larger trend in which enterprises are shifting from experimental AI pilots to full-scale production adoption. According to recent market research, global spending on generative AI infrastructure is expected to exceed $200 billion by 2028.

However, the rapid expansion of AI technologies has also raised concerns among regulators and privacy advocates. Critics argue that increased automation may affect employment in administrative and support roles, while also introducing new risks related to data security, misinformation, and algorithmic bias.

Government agencies in multiple countries are currently drafting regulatory frameworks aimed at balancing innovation with accountability. These proposed regulations include transparency requirements for AI-generated content, mandatory security audits, and stricter guidelines on training data usage.

Despite these concerns, investors responded positively to the announcement, with the company’s stock price rising nearly 6% during afternoon trading. Executives emphasized that responsible AI deployment remains central to their long-term strategy and pledged continued collaboration with policymakers, researchers, and enterprise customers.
"""

inputs = tokenizer(
    "summarize: " + article,
    return_tensors="pt"
).to(device)

output = model.generate(inputs["input_ids"], max_length=20)

print(tokenizer.decode(output[0], skip_special_tokens=True))

article = """
Global technology companies are increasing investments in artificial intelligence as competition in the sector continues to intensify. On Tuesday, a leading multinational software company announced a new suite of AI-powered productivity tools designed to automate repetitive office tasks, generate reports, and assist developers with code generation.

The company stated that the new tools will be integrated directly into its existing cloud ecosystem, allowing businesses to deploy AI assistants across email, documentation platforms, customer service workflows, and internal analytics dashboards.

Industry analysts believe this move is part of a larger trend in which enterprises are shifting from experimental AI pilots to full-scale production adoption. According to recent market research, global spending on generative AI infrastructure is expected to exceed $200 billion by 2028.

However, the rapid expansion of AI technologies has also raised concerns among regulators and privacy advocates. Critics argue that increased automation may affect employment in administrative and support roles, while also introducing new risks related to data security, misinformation, and algorithmic bias.

Government agencies in multiple countries are currently drafting regulatory frameworks aimed at balancing innovation with accountability. These proposed regulations include transparency requirements for AI-generated content, mandatory security audits, and stricter guidelines on training data usage.

Despite these concerns, investors responded positively to the announcement, with the company’s stock price rising nearly 6% during afternoon trading. Executives emphasized that responsible AI deployment remains central to their long-term strategy and pledged continued collaboration with policymakers, researchers, and enterprise customers.
"""

print(generate_headline(article))
print(generate_multiple_headlines(article))

